### ISSUE TITLE
Enviar um email para a lista do Tá Safo com o novo Bizu bem votado!

### ISSUE THREAD

**Issue by pigor** [tasafo/bizusafo#16]

**Comment by adailtulima** [comment]
Pessoal, que tal deixar esta funcionalidade configurável para enviar a um email especifico cada vez que um evento atingir um nivel X de aprovação ?

**Comment by pigor** [comment]
é uma boa mesmo deixar configurado, poderia ser uma fórmula mágica também que pegasse uma proporção dos votos com a média de aprovação dos demais, algo assim!

**Comment by pigor** [comment]
com o envio por email para os usuários do Bizusafo, não sei se ainda tem relevância essa issue, o que vocês acham?

**Comment by felipeik** [comment]
pode fechar pra mim

o trafego ta mt baixo pra ordenar o emails por votacao ainda
