### ISSUE TITLE
Escrever testes para as funcionalidades existentes

### ISSUE THREAD

**Issue by fabiolnm** [tasafo/bizusafo#34]
Por ser um projeto aberto, há um risco maior de ocorrerem regressões entre os commits dos diversos colaboradores.

O ideal é que a cobertura ficasse o mais próximo de 100%.

Atualmente a aplicação está configurada com RSpec, mas se houver consenso, seria uma oportunidade interessante de se usar MiniTest. 

O que acham?

**Comment by pigor** [comment]
não houve nenhum responsável pela mudança e nem novos argumentos, então vou fechar a issue.
