### ISSUE TITLE
Permitir editar post e/ou comentário durante X minutos

### ISSUE THREAD

**Issue by mfandrade** [tasafo/bizusafo#57]
Às vezes logo depois que comento percebo que cometi um erro de português.  Seria bom ter a possibilidade de editar o que se escreve, pelo menos nos X minutos (p.ex., 5min) depois de submetido.

**Comment by pigor** [comment]
acredito que essa issue já foi atendida, o único campo que não é possível editar é a url, caso ocorra algum equívoco na url pode apagar e refazer o bizu. Vou fechar a issue, caso não concorde podemos retomar a discussão.
