### ISSUE TITLE
Bug ao autenticar pelo facebook

### ISSUE THREAD

**Issue by mbgarcia** [tasafo/bizusafo#75]

**Comment by fabiolnm** [comment]
Este bug é o que ocorre ao tentar autenticar no link do +1?

![screen shot 2015-04-14 at 12 34 40 pm](https://cloud.githubusercontent.com/assets/508671/7140623/af1dc638-e2a2-11e4-89be-093644ee0734.png)

**Comment by pigor** [comment]
Acontece também no botão do Facebook na tela de login e/ou cadastro

**Comment by felipeik** [comment]
ja to ajeitando! o facebook removeu uma feature... vou pushar com essa feature resolvida, mas nao sei  o quanto vai afetar a expiracao do login
